[build]
jobs = 32 

[net]
git-fetch-with-cli = true

[profile.build-speed]
inherits = "dev" 
opt-level = 1           
debug = false  
incremental = true  
codegen-units = 8     
overflow-checks = false  
debug-assertions = false  


[profile.release]
opt-level = 0
incremental = true
codegen-units = 256
lto = false
overflow-checks = false
debug-assertions = false