[build]
jobs = 32 

[net]
git-fetch-with-cli = true

[profile.build-speed]
inherits = "dev" 
opt-level = 1           
debug = false  
incremental = true  
lto = false
codegen-units = 8     
overflow-checks = false  
debug-assertions = false  
