name: "CI: Build Docker Images"
on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  setup:
    name: Setup Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3  
      - name: Build & Cache Image
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            --tag my-org/my-image:latest .