name: "CI: Build Docker Images"
on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  setup:
    name: Setup Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3  
        with:
            builder: builder-main
            install: false
      - name: Cache Docker Buildx
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-cache-  
            
      - uses: dtolnay/rust-toolchain@1.86
            
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-targets: true        # caches your target/ directory
          cache-all-crates: true
          shared-key: rust-cache-${{ hashFiles('**/Cargo.lock') }}
          save-if: ${{ github.ref == 'refs/heads/main' }}            
          
      - name: Build & Cache Image
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            --tag my-org/my-image:latest .          